[project]
name = "example-kafka-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kafka-python>=2.0.5",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
