---
name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python:
          - "3.12"
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - run: cp example.env .env
      - run: docker compose --progress plain up --no-color --quiet-pull --detach
      - run: docker compose exec minio /usr/bin/mc ready local
      - run: docker compose exec minio /usr/bin/mc alias set local http://localhost:9000 minioadmin minioadmin
      - run: docker compose exec minio /usr/bin/mc mb local/tansu
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{matrix.python}}
      - run: uv pip install kafka-python
